//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : orExpression.h
//  @ Date : 14.05.2020
//  @ Author : 
//
//


#if !defined(_OREXPRESSION_H)
#define _OREXPRESSION_H

#include "expression.h"

class orExpression : public expression {
private:
    expression* expOne;
    expression* expTwo;
public:
    orExpression(expression *one, expression *two);
	bool interpret(std::string context);

};

#endif  //_OREXPRESSION_H
