//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : orExpression.cpp
//  @ Date : 14.05.2020
//  @ Author : 
//
//


#include "orExpression.h"

bool orExpression::interpret(std::string context) {
    return expOne->interpret(context) || expTwo->interpret(context);
}
orExpression::orExpression(expression *one, expression *two) {
    this->expOne=one;
    this->expTwo=two;
}

