//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : terminalExpression.h
//  @ Date : 14.05.2020
//  @ Author : 
//
//


#if !defined(_TERMINALEXPRESSION_H)
#define _TERMINALEXPRESSION_H

#include "expression.h"

class terminalExpression : public expression {
private:
    std::string data;
public:
    terminalExpression(std::string data);
	bool interpret(std::string context);
};

#endif  //_TERMINALEXPRESSION_H
