//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : terminalExpression.cpp
//  @ Date : 14.05.2020
//  @ Author : 
//
//


#include "terminalExpression.h"

bool terminalExpression::interpret(std::string context) {
    return context==this->data;
}
terminalExpression::terminalExpression(std::string data) {
    this->data=data;
}

