//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : auctionHouse.cpp
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#include "auctionHouse.h"

void auctionHouse::addAuction(command *command) {
    this->commands.emplace_back(command);
}

void auctionHouse::closeAuctions() {
    for(command *toExecute: commands)
        toExecute->execute();
}

