//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : buyItem.cpp
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#include "buyItem.h"
buyItem::buyItem(Item *item){
    this->item=item;
}
void buyItem::execute() {
    item->buy();
}

