//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : buyItem.h
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#if !defined(_BUYITEM_H)
#define _BUYITEM_H

#include "command.h"
#include "Item.h"

class buyItem : public command {
private:
    Item *item;
public:
    buyItem(Item *item);
	void execute();
};

#endif  //_BUYITEM_H
