//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : command.h
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#if !defined(_COMMAND_H)
#define _COMMAND_H


class command {
public:
	virtual void execute()=0;
};

#endif  //_COMMAND_H
