//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.cpp
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#include "Item.h"

Item::Item(std::string name){
    this->name=name;
}
void Item::buy() {
    std::cout<<"buying: "<<name<<'\n';
}

void Item::sell() {
    std::cout<<"selling: "<<name<<'\n';
}

