//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sellItem.cpp
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#include "sellItem.h"

sellItem::sellItem(Item *item) {
    this->item=item;
}
void sellItem::execute() {
    item->sell();
}