//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sortowanie.cpp
//  @ Date : 11.05.2020
//  @ Author : 
//
//


#include "sortowanie.h"

void sortowanie::sortuj(std::vector<int> &ref) {
    //tutaj jest jakis algorytm sortujacy wykorzystujacy nasz comapare

    comparator(ref[0],ref[1]);
}

