//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sortowanieRosnaco.h
//  @ Date : 11.05.2020
//  @ Author : 
//
//


#if !defined(_SORTOWANIEROSNACO_H)
#define _SORTOWANIEROSNACO_H

#include "sortowanie.h"
#include <iostream>
class sortowanieRosnaco : public sortowanie {
public:
    bool comparator(int, int);
};

#endif  //_SORTOWANIEROSNACO_H
