//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sortowanieMalejaco.cpp
//  @ Date : 11.05.2020
//  @ Author : 
//
//


#include "sortowanieMalejaco.h"

bool sortowanieMalejaco::comparator(int a,int b) {
    std::cout<<"sortuje malejaco";
    return a<b;
}

