//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sortowanieMalejaco.h
//  @ Date : 11.05.2020
//  @ Author : 
//
//


#if !defined(_SORTOWANIEMALEJACO_H)
#define _SORTOWANIEMALEJACO_H

#include "sortowanie.h"
#include <iostream>
class sortowanieMalejaco : public sortowanie {
public:
    bool comparator(int, int);
};

#endif  //_SORTOWANIEMALEJACO_H
