//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sortowanieRosnaco.cpp
//  @ Date : 11.05.2020
//  @ Author : 
//
//


#include "sortowanieRosnaco.h"

bool sortowanieRosnaco::comparator(int a, int b) {
    std::cout<<"sortuje rosnaco";
    return a>b;
}

