//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sortowanie.h
//  @ Date : 11.05.2020
//  @ Author : 
//
//


#if !defined(_SORTOWANIE_H)
#define _SORTOWANIE_H

#include <algorithm>
#include <vector>
class sortowanie {
public:
	void sortuj(std::vector<int> &ref);
	virtual bool comparator(int, int);
};

#endif  //_SORTOWANIE_H
