//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : axe.h
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#if !defined(_AXE_H)
#define _AXE_H

class axe : public Weapon {
private:
    std::string type="axe";
public:
    std::string getType(){return type;}
};

#endif  //_AXE_H
