//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : axePattern.h
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#if !defined(_AXEPATTERN_H)
#define _AXEPATTERN_H
#include "Creator.h"

class axePattern : public Creator {
public:
	Weapon* createWeapon();
};

#endif  //_AXEPATTERN_H
