//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Creator.cpp
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#include "Creator.h"

Weapon* Creator::createWeapon() {

}

