//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : polearmPattern.h
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#if !defined(_POLEARMPATTERN_H)
#define _POLEARMPATTERN_H
#include "Creator.h"

class polearmPattern : public Creator {
public:
	Weapon* createWeapon();
};

#endif  //_POLEARMPATTERN_H
