//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : polearmPattern.cpp
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#include "polearmPattern.h"

Weapon* polearmPattern::createWeapon() {
    std::cout<<"creating polearm\n";
    return new polearm();
}

