//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : swordPattern.cpp
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#include "swordPattern.h"

Weapon* swordPattern::createWeapon() {
    //std::cout<<"creating sword\n";
    return new sword();
}

