//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sword.h
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#if !defined(_SWORD_H)
#define _SWORD_H

class sword : public Weapon {
    std::string type="Sword";

public:
    std::string getType(){return type;}
};

#endif  //_SWORD_H
