//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : swordPattern.h
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#if !defined(_SWORDPATTERN_H)
#define _SWORDPATTERN_H

#include "Creator.h"

class swordPattern : public Creator {
public:
	Weapon* createWeapon();
};

#endif  //_SWORDPATTERN_H
