//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Weaponsmith.cpp
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#include "Weaponsmith.h"

Weapon* Weaponsmith::createWeapon(Creator* pattern) {
    return pattern->createWeapon();
}