//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Weaponsmith.h
//  @ Date : 30.04.2020
//  @ Author : 
//
//


#if !defined(_WEAPONSMITH_H)
#define _WEAPONSMITH_H

#include "Creator.h"

class Weaponsmith {
public:
	Weapon* createWeapon(Creator* pattern);
};

#endif  //_WEAPONSMITH_H
