//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Koszyk.h
//  @ Date : 04.05.2020
//  @ Author : 
//
//


#if !defined(_KOSZYK_H)
#define _KOSZYK_H

#include "produkt.h"
#include <vector>
#include <iostream>
class Koszyk : public produkt {
public:
	void dodaj(produkt* prod);
	void sprzedaj();
private:
	std::vector<produkt*> produkty;
};

#endif  //_KOSZYK_H
