//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Koszyk.cpp
//  @ Date : 04.05.2020
//  @ Author : 
//
//


#include "Koszyk.h"

void Koszyk::dodaj(produkt* prod) {
    this->produkty.push_back(prod);
}

void Koszyk::sprzedaj() {
    for(produkt* prod : produkty)
        prod->sprzedaj();
}

