//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : produktA.h
//  @ Date : 04.05.2020
//  @ Author : 
//
//


#if !defined(_PRODUKTA_H)
#define _PRODUKTA_H

#include "produkt.h"
#include <iostream>
class produktA : public produkt {
public:
	void sprzedaj();
};

#endif  //_PRODUKTA_H
