//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : produktB.h
//  @ Date : 04.05.2020
//  @ Author : 
//
//


#if !defined(_PRODUKTB_H)
#define _PRODUKTB_H

#include "produkt.h"
#include <iostream>
class produktB : public produkt {
public:
	void sprzedaj();
};

#endif  //_PRODUKTB_H
