//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : produktB.cpp
//  @ Date : 04.05.2020
//  @ Author : 
//
//


#include "produktB.h"

void produktB::sprzedaj() {
    std::cout<<"produkt B jest sprzedawany\n";
}

