//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : produkt.h
//  @ Date : 04.05.2020
//  @ Author : 
//
//


#if !defined(_PRODUKT_H)
#define _PRODUKT_H


class produkt {
public:
	virtual void sprzedaj()=0;
};

#endif  //_PRODUKT_H
