//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : grassTexture.cpp
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#include "grassTexture.h"

void grassTexture::printInfo() {
    std::cout<<"this is grass texture\n";
}

