//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : grassTexture.h
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#if !defined(_GRASSTEXTURE_H)
#define _GRASSTEXTURE_H

#include "texture.h"

class grassTexture : public texture {
public:
	void printInfo();
};

#endif  //_GRASSTEXTURE_H
