//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : grassTextureCreator.h
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#if !defined(_GRASSTEXTURECREATOR_H)
#define _GRASSTEXTURECREATOR_H

#include "textureCreatorHandler.h"
#include "grassTexture.h"

class grassTextureCreator : public textureCreatorHandler {
private:
    textureCreatorHandler *nextStep=nullptr;
public:
	texture* create(std::string name);
	void setNextStep(textureCreatorHandler *step);
};

#endif  //_GRASSTEXTURECREATOR_H
