//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : rockTextureCreator.h
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#if !defined(_ROCKTEXTURECREATOR_H)
#define _ROCKTEXTURECREATOR_H

#include "textureCreatorHandler.h"
#include "rockTexture.h"

class rockTextureCreator : public textureCreatorHandler {
private:
    textureCreatorHandler *nextStep=nullptr;
public:
	texture* create(std::string name);
	void setNextStep(textureCreatorHandler *step);
};

#endif  //_ROCKTEXTURECREATOR_H
