//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : rockTextureCreator.cpp
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#include "rockTextureCreator.h"
#include "textureCreatorHandler.h"

texture* rockTextureCreator::create(std::string name) {
    if(name=="rock")
        return new rockTexture;

    if(nextStep)
        return nextStep->create(name);

    return nullptr;
}

void rockTextureCreator::setNextStep(textureCreatorHandler *step) {
    this->nextStep=step;
}

