//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : rockTexture.h
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#if !defined(_ROCKTEXTURE_H)
#define _ROCKTEXTURE_H

#include "texture.h"

class rockTexture : public texture {
public:
	void printInfo();
};

#endif  //_ROCKTEXTURE_H
