//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : rockTexture.cpp
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#include "rockTexture.h"

void rockTexture::printInfo() {
    std::cout<<"this is rock texture\n";
}

