//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : textureFactory.cpp
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#include "textureFactory.h"

texture* textureFactory::getTexture(std::string name) {
    auto result=textures.find(name);

    if(result==textures.end()){
        texture *resultTexture=createTexture->create(name);
        textures[name]=resultTexture;
        return resultTexture;
    }
    return result->second;
}
textureFactory::textureFactory(textureCreatorHandler *createTexture) {
    this->createTexture=createTexture;
}

