//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : texture.h
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#if !defined(_TEXTURE_H)
#define _TEXTURE_H

#include <string>
#include <iostream>
class texture {
public:
	virtual void printInfo()=0;
};

#endif  //_TEXTURE_H
