//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : textureFactory.h
//  @ Date : 18.05.2020
//  @ Author : 
//
//


#if !defined(_TEXTUREFACTORY_H)
#define _TEXTUREFACTORY_H

#include "textureCreatorHandler.h"
#include "texture.h"
#include <map>
class textureFactory {
private:
    textureCreatorHandler *createTexture;
    std::map<std::string, texture*> textures;
public:
    textureFactory(textureCreatorHandler *createTexture);
	texture* getTexture(std::string name);
};

#endif  //_TEXTUREFACTORY_H
