//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : axe.cpp
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#include "axe.h"

void axe::setTransmogrification(transmogrification* transmogrificationType) {
    this->transmogrificationType=transmogrificationType;
}

void axe::showWeapon() {
    std::cout<<"this is axe and it looks like: "<<transmogrificationType->getTexture()<<'\n';
}
axe::axe(transmogrification* transmogrificationType) {
    this->transmogrificationType=transmogrificationType;
}
