//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : axeTransmogrification.h
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#if !defined(_AXETRANSMOGRIFICATION_H)
#define _AXETRANSMOGRIFICATION_H

#include "transmogrification.h"
class axeTransmogrification: public transmogrification {
public:
    std::string getTexture();
};

#endif  //_AXETRANSMOGRIFICATION_H
