//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : axeTransmogrification.cpp
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#include "axeTransmogrification.h"

std::string axeTransmogrification::getTexture() {
    return "axe";
}

