//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : staffTransmogrification.cpp
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#include "staffTransmogrification.h"

std::string staffTransmogrification::getTexture() {
    return "staff";
}

