//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : staff.cpp
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#include "staff.h"

void staff::setTransmogrification(transmogrification* transmogrificationType) {
    this->transmogrificationType=transmogrificationType;
}

void staff::showWeapon() {
    std::cout<<"this is staff and it looks like: "<<transmogrificationType->getTexture()<<'\n';
}
staff::staff(transmogrification *transmogrificationType) {
    this->transmogrificationType=transmogrificationType;
}

