//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : staffTransmogrification.h
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#if !defined(_STAFFTRANSMOGRIFICATION_H)
#define _STAFFTRANSMOGRIFICATION_H

#include "transmogrification.h"

class staffTransmogrification: public transmogrification {
public:
    std::string getTexture();
};

#endif  //_STAFFTRANSMOGRIFICATION_H
