//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : staff.h
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#if !defined(_STAFF_H)
#define _STAFF_H

#include "weapon.h"

class staff : public weapon {
protected:
    transmogrification* transmogrificationType;
public:
    staff(transmogrification* transmogrificationType);
	void setTransmogrification(transmogrification* transmogrificationType);
	void showWeapon();
};

#endif  //_STAFF_H
