//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sword.cpp
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#include "sword.h"

void sword::setTransmogrification(transmogrification* transmogrificationType) {
    this->transmogrificationType=transmogrificationType;
}

void sword::showWeapon() {
    std::cout<<"this is sword and it looks like: "<<transmogrificationType->getTexture()<<'\n';
}
sword::sword(transmogrification *transmogrificationType) {
    this->transmogrificationType=transmogrificationType;
}

