//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : swordTransmogrification.cpp
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#include "swordTransmogrification.h"

std::string swordTransmogrification::getTexture() {
    return "sword";
}

