//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : sword.h
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#if !defined(_SWORD_H)
#define _SWORD_H

#include "weapon.h"

class sword : public weapon {
protected:
    transmogrification* transmogrificationType;
public:
    sword(transmogrification* transmogrificationType);
    void setTransmogrification(transmogrification* transmogrificationType);
    void showWeapon();
};

#endif  //_SWORD_H
