//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : swordTransmogrification.h
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#if !defined(_SWORDTRANSMOGRIFICATION_H)
#define _SWORDTRANSMOGRIFICATION_H

#include "transmogrification.h"

class swordTransmogrification: public transmogrification{
public:
    std::string getTexture();
};

#endif  //_SWORDTRANSMOGRIFICATION_H
