//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : transmogrification.h
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#if !defined(_TRANSMOGRIFICATION_H)
#define _TRANSMOGRIFICATION_H

#include <string>

class transmogrification {
public:
	virtual std::string getTexture()=0;
};

#endif  //_TRANSMOGRIFICATION_H
