//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : weapon.h
//  @ Date : 17.05.2020
//  @ Author : 
//
//


#if !defined(_WEAPON_H)
#define _WEAPON_H

#include "transmogrification.h"
#include <iostream>
class weapon {
protected:
    transmogrification* transmogrificationType=nullptr;
public:
	virtual void setTransmogrification(transmogrification* transmogrificationType)=0;
	virtual void showWeapon()=0;
};

#endif  //_WEAPON_H
