//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : samolotowy.h
//  @ Date : 13.05.2020
//  @ Author : 
//
//


#if !defined(_SAMOLOTOWY_H)
#define _SAMOLOTOWY_H

#include "tryb.h"

class samolotowy : public tryb {
public:
	void rozmowa();
	void sms();
	void internet();
};

#endif  //_SAMOLOTOWY_H
