//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : samolotowy.cpp
//  @ Date : 13.05.2020
//  @ Author : 
//
//


#include "samolotowy.h"

void samolotowy::rozmowa() {
    std::cout<<"rozmowy wyłączone\n";
}

void samolotowy::sms() {
    std::cout<<"sms'y wyłączone\n";
}

void samolotowy::internet() {
    std::cout<<"internet wyłączony\n";
}

