//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : telefon.h
//  @ Date : 13.05.2020
//  @ Author : 
//
//


#if !defined(_TELEFON_H)
#define _TELEFON_H

#include "tryb.h"

class telefon {
public:
    telefon(tryb* tryb);
    void ustawTryb(tryb* nowy_tryb);
	void dzwon();
	void wyslij_sms();
	void przegladaj_internet();
private:
	tryb* tryb_telefonu;
};

#endif  //_TELEFON_H
