//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : tryb.h
//  @ Date : 13.05.2020
//  @ Author : 
//
//


#if !defined(_TRYB_H)
#define _TRYB_H

#include <iostream>

class tryb {
public:
	virtual void rozmowa()=0;
	virtual void sms()=0;
	virtual void internet()=0;
};

#endif  //_TRYB_H
