//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : wyciszony.cpp
//  @ Date : 13.05.2020
//  @ Author : 
//
//


#include "wyciszony.h"

void wyciszony::rozmowa() {
    std::cout<<"mozna dzwonic, ale dzwonek wylaczony\n";
}

void wyciszony::sms() {
    std::cout<<"mozna pisac sms, ale dzwonek wylaczony\n";
}

void wyciszony::internet() {
    std::cout<<"mozna korzystac z internetu\n";
}

