//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : wyciszony.h
//  @ Date : 13.05.2020
//  @ Author : 
//
//


#if !defined(_WYCISZONY_H)
#define _WYCISZONY_H

#include "tryb.h"

class wyciszony : public tryb {
public:
	void rozmowa();
	void sms();
	void internet();
};

#endif  //_WYCISZONY_H
