//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : zwykly.cpp
//  @ Date : 13.05.2020
//  @ Author : 
//
//


#include "zwykly.h"

void zwykly::rozmowa() {
    std::cout<<"mozna dzwonic\n";
}

void zwykly::sms() {
    std::cout<<"mozna pisac\n";
}

void zwykly::internet() {
    std::cout<<"mozna uzywac internetu\n";
}

