//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : zwykly.h
//  @ Date : 13.05.2020
//  @ Author : 
//
//


#if !defined(_ZWYKLY_H)
#define _ZWYKLY_H

#include "tryb.h"

class zwykly : public tryb {
public:
	void rozmowa();
	void sms();
	void internet();
};

#endif  //_ZWYKLY_H
