//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Memento.cpp
//  @ Date : 10.05.2020
//  @ Author : 
//
//


#include "Memento.h"

Memento::Memento(int state) {
    this->state=state;
}

int Memento::getState() {
    return state;
}

