//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Memento.h
//  @ Date : 10.05.2020
//  @ Author : 
//
//


#if !defined(_MEMENTO_H)
#define _MEMENTO_H


class Memento {
private:
    int state;
public:
    Memento(int state);
	int getState();
};

#endif  //_MEMENTO_H
