//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : object.h
//  @ Date : 10.05.2020
//  @ Author : 
//
//


#if !defined(_OBJECT_H)
#define _OBJECT_H

#include "Memento.h"

class object {
private:
    int state;
public:
	Memento* createMemento();
	void restore(Memento* memento);
    int getState() const;
    void setState(int state);

};

#endif  //_OBJECT_H
