//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : object.cpp
//  @ Date : 10.05.2020
//  @ Author : 
//
//


#include "object.h"

Memento* object::createMemento() {
    return new Memento(state);
}

void object::restore(Memento* memento) {
    state=memento->getState();
}

int object::getState() const {
    return state;
}

void object::setState(int state) {
    object::state = state;
}

