//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : rememberedStates.h
//  @ Date : 10.05.2020
//  @ Author : 
//
//


#if !defined(_REMEMBEREDSTATES_H)
#define _REMEMBEREDSTATES_H

#include "Memento.h"
#include <vector>

class rememberedStates {
private:
    std::vector<Memento*> states;
public:
	Memento* get(int index);
    void add(Memento* memento);
};

#endif  //_REMEMBEREDSTATES_H
