//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : rememberedStates.cpp
//  @ Date : 10.05.2020
//  @ Author : 
//
//


#include "rememberedStates.h"

void rememberedStates::add(Memento* memento) {
    states.emplace_back(memento);
}

Memento* rememberedStates::get(int index) {
    return states[index];
}

