//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : konkretnyPlik.cpp
//  @ Date : 06.05.2020
//  @ Author : 
//
//


#include "konkretnyPlik.h"
konkretnyPlik::konkretnyPlik(std::string nazwa){
    this->nazwa=nazwa;
    //tutaj otwieram plik o podanej nazwie
    std::cout<<"otwieranie prawdziwego pliku\n";
}
konkretnyPlik::~konkretnyPlik(){
    std::cout<<"zamykanie prawdziwego pliku\n";
}
void konkretnyPlik::znajdz() {
    //tutaj funkcja do znajdowania jakichs wpisow w pliku
    std::cout<<"wyszukiwanie w pliku\n";
}

void konkretnyPlik::zapisz(std::string coZapisac) {
    //funkcja do zapisywania rzeczy pliku
    std::cout<<"zapisywanie w prawdziwym pliku\n";
}

