//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : konkretnyPlik.h
//  @ Date : 06.05.2020
//  @ Author : 
//
//


#if !defined(_KONKRETNYPLIK_H)
#define _KONKRETNYPLIK_H

#include "plik.h"

class konkretnyPlik : public plik{
private:
    std::string nazwa;
    std::fstream plik;
public:
    konkretnyPlik(std::string nazwa);
	void znajdz();
	void zapisz(std::string coZapisac);
	~konkretnyPlik();
};

#endif  //_KONKRETNYPLIK_H
