//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : proxyPlik.cpp
//  @ Date : 06.05.2020
//  @ Author : 
//
//


#include "proxyPlik.h"
proxyPlik::proxyPlik(std::string nazwa){
    this->nazwa=nazwa;
    wskaznikNaPlik=nullptr;
}
proxyPlik::~proxyPlik(){
    for(std::string tmp: rzeczyDoZapisania)
        wskaznikNaPlik->zapisz(tmp);
    delete wskaznikNaPlik;
}
void proxyPlik::znajdz() {
    if(wskaznikNaPlik== nullptr)
        wskaznikNaPlik=new konkretnyPlik(nazwa);
    wskaznikNaPlik->znajdz();
}

void proxyPlik::zapisz(std::string coZapisac) {
    std::cout<<"zapisuje w klasie proxy dzieki czemu latwo moge cofnac zmiany\n";
    this->rzeczyDoZapisania.push_back(coZapisac);
}

