//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Armour.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_ARMOUR_H)
#define _ARMOUR_H


class Armour {
public:
    virtual void printData()=0;
};

#endif  //_ARMOUR_H
