//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ArmourSet.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_ARMOURSET_H)
#define _ARMOURSET_H

#include "Head.h"
#include "Hands.h"
#include "Chest.h"

class ArmourSet {
public:
	virtual Armour* getHead()=0;
	virtual Armour* getChest()=0;
	virtual Armour* getHands()=0;
};

#endif  //_ARMOURSET_H
