//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Chest.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_CHEST_H)
#define _CHEST_H

#include "Armour.h"
#include <string>
#include <iostream>
class Chest : public Armour {
private:
    std::string type;
    std::string name;
public:

    Chest(std::string type);
    void printData();
};

#endif  //_CHEST_H
