//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ClothTypeFactory.cpp
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#include "ClothTypeFactory.h"

ClothTypeFactory::ClothTypeFactory() {
    this->type="cloth";
}
Armour* ClothTypeFactory::getHead() {
    return new Head(this->type);
}

Armour* ClothTypeFactory::getChest() {
    return new Chest(this->type);
}

Armour* ClothTypeFactory::getHands() {
    return new Hands(this->type);
}

