//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ClothTypeFactory.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_CLOTHTYPEFACTORY_H)
#define _CLOTHTYPEFACTORY_H

#include "ArmourSet.h"
#include <iostream>
class ClothTypeFactory : public ArmourSet {
private:
    std::string type;
public:

    ClothTypeFactory();
	Armour* getHead();
	Armour* getChest();
	Armour* getHands();
};

#endif  //_CLOTHTYPEFACTORY_H
