//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Hands.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_HANDS_H)
#define _HANDS_H

#include "Armour.h"
#include <string>
#include <iostream>
class Hands : public Armour {
private:
	std::string type;
	std::string name;
public:

	Hands(std::string type);
	void printData();
};

#endif  //_HANDS_H
