//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Head.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_HEAD_H)
#define _HEAD_H

#include "Armour.h"
#include <string>
#include <iostream>
class Head : public Armour {
private:
    std::string type;
    std::string name;
public:

    Head(std::string type);
    void printData();
};

#endif  //_HEAD_H
