//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MailTypeFactory.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_MAILTYPEFACTORY_H)
#define _MAILTYPEFACTORY_H

#include "ArmourSet.h"

class MailTypeFactory : public ArmourSet {
private:
    std::string type;
public:
    MailTypeFactory();
	Armour* getHead();
	Armour* getChest();
	Armour* getHands();
};

#endif  //_MAILTYPEFACTORY_H
