//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MailTypeFactory.cpp
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#include "MailTypeFactory.h"

MailTypeFactory::MailTypeFactory(){
    this->type="mail";
}
Armour* MailTypeFactory::getHead() {
    return new Head(this->type);
}

Armour* MailTypeFactory::getChest() {
    return new Chest(this->type);
}

Armour* MailTypeFactory::getHands() {
    return new Hands(this->type);
}

