//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PlateTypeFactory.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_PLATETYPEFACTORY_H)
#define _PLATETYPEFACTORY_H

#include "ArmourSet.h"

class PlateTypeFactory : public ArmourSet {
private:
    std::string type;
public:
    PlateTypeFactory();
	Armour* getHead();
	Armour* getChest();
	Armour* getHands();
};

#endif  //_PLATETYPEFACTORY_H
