//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PlateTypeFactory.cpp
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#include "PlateTypeFactory.h"

PlateTypeFactory::PlateTypeFactory(){
    this->type="plate";
}
Armour* PlateTypeFactory::getHead() {
    return new Head(this->type);
}

Armour* PlateTypeFactory::getChest() {
    return new Chest(this->type);
}

Armour* PlateTypeFactory::getHands() {
    return new Hands(this->type);
}

