//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SmithHold.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_SMITHHOLD_H)
#define _SMITHHOLD_H
#include "Smith.h"
#include <map>

class SmithHold {
public:
    SmithHold();
	std::vector<Armour*> *giveOrder(std::string typeOfArmour);
private:
	std::vector<Smith> smiths;
	std::map<std::string, ArmourSet*> patterns;
};

#endif  //_SMITHHOLD_H
