//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SmithHold.cpp
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#include "SmithHold.h"
SmithHold::SmithHold() {
    smiths.emplace_back(Smith());
    patterns["plate"]=new PlateTypeFactory();
    patterns["cloth"]=new ClothTypeFactory();
    patterns["mail"]=new MailTypeFactory();
}
std::vector<Armour*> *SmithHold::giveOrder(std::string typeOfArmour) {
    return smiths[0].makeSet(patterns[typeOfArmour]);
}

