//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Smith.cpp
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#include "Smith.h"

std::vector<Armour*> *Smith::makeSet(ArmourSet* pattern) {
    auto *newSet=new std::vector<Armour*>();
    newSet->emplace_back(pattern->getChest());
    newSet->emplace_back(pattern->getHands());
    newSet->emplace_back(pattern->getHead());

    return newSet;
}

