//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Smith.h
//  @ Date : 02.05.2020
//  @ Author : 
//
//


#if !defined(_SMITH_H)
#define _SMITH_H
#include "PlateTypeFactory.h"
#include "ClothTypeFactory.h"
#include "MailTypeFactory.h"
#include <vector>
#include <string>
class Smith {
public:
	std::vector<Armour*>* makeSet(ArmourSet* pattern);
};

#endif  //_SMITH_H
