//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : router.cpp
//  @ Date : 12.05.2020
//  @ Author : 
//
//


#include "router.h"

void router::pinguj(komputer* skad, komputer* dokad) {
    dokad->odbierzPing(skad);
}

