//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : router.h
//  @ Date : 12.05.2020
//  @ Author : 
//
//


#if !defined(_ROUTER_H)
#define _ROUTER_H

#include "komputer.h"
class router {
public:
	void pinguj(komputer* skad, komputer* dokad);
};

#endif  //_ROUTER_H
