//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : appleBuilder.cpp
//  @ Date : 15.05.2020
//  @ Author : 
//
//


#include "appleBuilder.h"
void appleBuilder::initializePhone(){
    applePhone=new Phone;
}
void appleBuilder::placeProcessor(){
    applePhone->setProcessor("rich apple processor");
}
void appleBuilder::placeRAM() {
    applePhone->setRAM("rich apple ram");
}

void appleBuilder::placeDisplay() {
    applePhone->setDisplay("rich saphire apple dispaly");
}

Phone* appleBuilder::getPhone() {
    return applePhone;
}

