//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : builder.h
//  @ Date : 15.05.2020
//  @ Author : 
//
//


#if !defined(_BUILDER_H)
#define _BUILDER_H

#include "Phone.h"

class builder {
public:
    virtual void initializePhone()=0;
	virtual void placeProcessor()=0;
	virtual void placeRAM()=0;
	virtual void placeDisplay()=0;
	virtual Phone* getPhone()=0;
};

#endif  //_BUILDER_H
