//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : engineer.cpp
//  @ Date : 15.05.2020
//  @ Author : 
//
//


#include "engineer.h"

Phone* engineer::getPhone(builder* builderReference) {
    //tu jest schemat tworzenia instancji naszej klasy, w tym przypadku jest to proste wywołanie kilku metod
    builderReference->initializePhone();
    builderReference->placeProcessor();
    builderReference->placeRAM();
    builderReference->placeDisplay();

    return builderReference->getPhone();
}

