//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : engineer.h
//  @ Date : 15.05.2020
//  @ Author : 
//
//


#if !defined(_ENGINEER_H)
#define _ENGINEER_H

#include "Phone.h"
#include "builder.h"

class engineer {
public:
	Phone* getPhone(builder* builderReference);
};

#endif  //_ENGINEER_H
