//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Phone.cpp
//  @ Date : 15.05.2020
//  @ Author : 
//
//


#include "Phone.h"

void Phone::setProcessor(std::string processorPlaceholder) {
    processor=processorPlaceholder;
}

void Phone::setRAM(std::string RAMPlaceholder) {
    RAM=RAMPlaceholder;
}

void Phone::setDisplay(std::string displayPlaceholder) {
    display=displayPlaceholder;
}

void Phone::printInfo(){
    std::cout<<"processor: "<<processor<<"\nRAM: "<<RAM<<"\ndisplay: "<<display<<'\n';
}


