//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : samsungBuilder.cpp
//  @ Date : 15.05.2020
//  @ Author : 
//
//


#include "samsungBuilder.h"
void samsungBuilder::initializePhone(){
    samsungPhone=new Phone;
}
void samsungBuilder::placeProcessor() {
    samsungPhone->setProcessor("samsung processor");
}

void samsungBuilder::placeRAM() {
    samsungPhone->setRAM("samsung RAM");
}

void samsungBuilder::placeDisplay() {
    samsungPhone->setDisplay("samsung display");
}

Phone* samsungBuilder::getPhone() {
    return samsungPhone;
}

