//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : samsungBuilder.h
//  @ Date : 15.05.2020
//  @ Author : 
//
//


#if !defined(_SAMSUNGBUILDER_H)
#define _SAMSUNGBUILDER_H

#include "builder.h"

class samsungBuilder : public builder {
private:
    Phone* samsungPhone;
public:
    void initializePhone();
	void placeProcessor();
	void placeRAM();
	void placeDisplay();
	Phone* getPhone();
};

#endif  //_SAMSUNGBUILDER_H
