//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : adapterVGA.h
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#if !defined(_ADAPTERVGA_H)
#define _ADAPTERVGA_H

#include "urzadzenieVGA.h"
#include "urzadzenieHDMI.h"
class adapterVGA : public urzadzenieVGA {
private:
	urzadzenieHDMI* monitor;
public:
    adapterVGA(urzadzenieHDMI *ptr);
    void wyswietlVGA();
};

#endif  //_ADAPTERVGA_H
