//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : monitorVGA.cpp
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#include "monitorVGA.h"

void monitorVGA::wyswietlVGA() {
    std::cout<<"wyswietlanie z vga\n";
}

