//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : monitorVGA.h
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#if !defined(_MONITORVGA_H)
#define _MONITORVGA_H

#include "urzadzenieVGA.h"

class monitorVGA : public urzadzenieVGA {
public:
	void wyswietlVGA();
};

#endif  //_MONITORVGA_H
