//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : monitorHDMI.cpp
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#include "monitorHDMI.h"

void monitorHDMI::wyswietlHDMI() {
    std::cout<<"wyswietlanie hdmi\n";
}

