//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : monitorHDMI.h
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#if !defined(_MONITORHDMI_H)
#define _MONITORHDMI_H

#include "urzadzenieHDMI.h"

class monitorHDMI : public urzadzenieHDMI {
public:
	void wyswietlHDMI();
};

#endif  //_MONITORHDMI_H
