//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : staryKomputerek.h
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#if !defined(_STARYKOMPUTEREK_H)
#define _STARYKOMPUTEREK_H
#include "urzadzenieVGA.h"
#include "urzadzenieHDMI.h"
class staryKomputerek {
private:
    urzadzenieVGA* monitor;
public:
    staryKomputerek(urzadzenieVGA *monitor);
	void wyswietl();
};

#endif  //_STARYKOMPUTEREK_H
