//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : staryKomputerek.cpp
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#include "staryKomputerek.h"
staryKomputerek::staryKomputerek(urzadzenieVGA *monitor){
    this->monitor=monitor;
}
void staryKomputerek::wyswietl() {
    monitor->wyswietlVGA();
}

