//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : urzadzenieHDMI.h
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#if !defined(_URZADZENIEHDMI_H)
#define _URZADZENIEHDMI_H

#include <iostream>

class urzadzenieHDMI {
public:
	virtual void wyswietlHDMI()=0;
};

#endif  //_URZADZENIEHDMI_H
