//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : urzadzenieVGA.h
//  @ Date : 08.05.2020
//  @ Author : 
//
//


#if !defined(_URZADZENIEVGA_H)
#define _URZADZENIEVGA_H

#include <iostream>

class urzadzenieVGA {
public:
	virtual void wyswietlVGA()=0;
};

#endif  //_URZADZENIEVGA_H
