//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Borrow.h
//  @ Date : 16.05.2020
//  @ Author : 
//
//


#if !defined(_BORROW_H)
#define _BORROW_H

#include "merchantHandler.h"

class Borrow : public merchantHandler {
public:
	void handle(std::string request);
	void setNextStep(merchantHandler* step);
private:
	merchantHandler* nextStep=nullptr;
};

#endif  //_BORROW_H
