//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Borrow.cpp
//  @ Date : 16.05.2020
//  @ Author : 
//
//


#include "Borrow.h"

void Borrow::handle(std::string request) {
    if(request=="borrow"){
        std::cout<<"borrowing items\n";
        return;
    }
    if(nextStep) {
        std::cout<<"delegating actions\n";
        this->nextStep->handle(request);
    }
}

void Borrow::setNextStep(merchantHandler* step) {
    this->nextStep=step;
}

