//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Buy.h
//  @ Date : 16.05.2020
//  @ Author : 
//
//


#if !defined(_BUY_H)
#define _BUY_H

#include "merchantHandler.h"

class Buy : public merchantHandler {
public:
	void handle(std::string request);
	void setNextStep(merchantHandler* step);
private:
	merchantHandler* nextStep=nullptr;
};

#endif  //_BUY_H
