//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : merchantHandler.h
//  @ Date : 16.05.2020
//  @ Author : 
//
//


#if !defined(_MERCHANTHANDLER_H)
#define _MERCHANTHANDLER_H
#include <string>
#include <iostream>

class merchantHandler {
public:
	virtual void handle(std::string request) = 0;
	virtual void setNextStep(merchantHandler* step) = 0;
};

#endif  //_MERCHANTHANDLER_H
