//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sell.h
//  @ Date : 16.05.2020
//  @ Author : 
//
//


#if !defined(_SELL_H)
#define _SELL_H

#include "merchantHandler.h"

class Sell : public merchantHandler {
public:
	void handle(std::string request);
	void setNextStep(merchantHandler* step);
private:
	merchantHandler* nextStep=nullptr;
};

#endif  //_SELL_H
