//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sell.cpp
//  @ Date : 16.05.2020
//  @ Author : 
//
//


#include "Sell.h"

void Sell::handle(std::string request) {
    if(request=="sell"){
        std::cout<<"selling items\n";
        return;
    }
    if(nextStep) {
        std::cout<<"delegating actions\n";
        this->nextStep->handle(request);
    }
}

void Sell::setNextStep(merchantHandler* step){
    this->nextStep=step;
}

