//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cake.h
//  @ Date : 03.05.2020
//  @ Author : 
//
//


#if !defined(_CAKE_H)
#define _CAKE_H

#include <string>

class cake {
public:
	virtual cake* clone()=0;
    virtual void setName(std::string newName)=0;
    virtual std::string getName()=0;
};

#endif  //_CAKE_H
