//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : chocolate_cake.cpp
//  @ Date : 03.05.2020
//  @ Author : 
//
//


#include "chocolate_cake.h"
std::string chocolate_cake::getName() {return this->name;}
void chocolate_cake::setName(std::string newName) {this->name=newName;}
cake* chocolate_cake::clone() {
    //tutaj kopiujemy stan obiektu do nowego obiektu, bo jego od nowa stworzenie byłoby kosztowne
    cake* result=new chocolate_cake();
    result->setName(this->getName());

    return result;
}

