//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : chocolate_cake.h
//  @ Date : 03.05.2020
//  @ Author : 
//
//


#if !defined(_CHOCOLATE_CAKE_H)
#define _CHOCOLATE_CAKE_H

#include "cake.h"
class chocolate_cake : public cake {
    std::string name;
public:
	cake* clone();
    void setName(std::string newName);
    std::string getName();
};

#endif  //_CHOCOLATE_CAKE_H
